# python/m5/tools/html.py
"""将周报 Markdown 渲染为带样式、已净化的 HTML 页面。

属于主 agent。HTML 外壳为固定可信模板；周报正文来自不可信的网页搜索结果，
在写入页面前经白名单净化器（nh3）处理 — 剥离搜索结果可能夹带的
<script>、onerror= 等。
"""

from __future__ import annotations

import markdown as md
import nh3
from langchain_core.tools import tool

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }}
  h1 {{ font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }}
  h2 {{ color: #006DDD; margin-top: 1.6em; }}
  footer {{ margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
{body}
<footer>Generated by the Chinook Sales Assistant.</footer>
</body>
</html>"""


@tool
def markdown_to_html(markdown_text: str, title: str = "This Week in Music") -> str:
    """将 Markdown 周报转换为完整、带样式的 HTML 页面。
    返回完整 HTML 文档字符串。"""
    body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    # 正文由不可信网页搜索构建，渲染前做白名单净化。
    # 模板本身可信，保持原样。
    body = nh3.clean(body)
    return _HTML_TEMPLATE.format(title=title, body=body)
